export const LABEL_LIST: object = {
  barcode: 'Barcode',
  categoryId: 'Category',
  description: 'Description',
  email: 'Email',
  image: 'Image',
  images: 'Imags',
  mrp: 'Retail Price',
  name: 'Name',
  password: 'Password',
  phone: 'Phone number',
  point: 'Point',
  price: 'Price',
  priority: 'Priority',
  size: 'Size',
  thumb: 'Thumb',
};
