export const LABEL_LIST: object = {
  address: 'Address',
  barcode: 'Barcode',
  customer: 'Customer',
  cus_add1: 'Address line 1',
  cus_add2: 'Address line 2 (optional)',
  cus_city: 'City',
  cus_country: 'Country',
  categoryId: 'Category',
  confirmPassword: 'Confirm Password',
  description: 'Description',
  deliveryInstruction: 'Any delivery instruction? (optional)',
  email: 'Email',
  image: 'Image',
  images: 'Imags',
  inventoryType: 'Inventory Type',
  latitude: 'Latitude',
  longitude: 'Longitude',
  mrp: 'Retail Price',
  name: 'Name',
  newPassword: 'New Password',
  oldPassword: 'Old Password',
  otp: 'OTP',
  password: 'Password',
  paymentMethod: 'Payment Method',
  phone: 'Phone number',
  point: 'Point',
  price: 'Price',
  priority: 'Priority',
  product: 'Product',
  reference: 'Reference',
  size: 'Size',
  supplierId: 'Supplier',
  supplier: 'Supplier',
  thumb: 'Thumb',
  userId: 'User',
  warehouseId: 'Warehouse',
  warehouse: 'Warehouse',
};
