export const LABEL_LIST: object = {
  address: 'Address',
  barcode: 'Barcode',
  categoryId: 'Category',
  description: 'Description',
  email: 'Email',
  image: 'Image',
  images: 'Imags',
  inventoryType: 'Inventory Type',
  latitude: 'Latitude',
  longitude: 'Longitude',
  mrp: 'Retail Price',
  name: 'Name',
  password: 'Password',
  phone: 'Phone number',
  point: 'Point',
  price: 'Price',
  priority: 'Priority',
  product: 'Product',
  reference: 'Reference',
  size: 'Size',
  supplierId: 'Supplier',
  supplier: 'Supplier',
  thumb: 'Thumb',
  userId: 'User',
  warehouseId: 'Warehouse',
  warehouse: 'Warehouse',
};
